apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:wmTcV/P1hKnPzK89HuSiVF5Lq2fZX/T6pt0W72WyYwIBcpgzcEjkhMc3HQitrcNKAye/E9BUP67473cmtjhpiM/XycfjUBrucHWFXFVolGcSIzJmC28jwg==,iv:7X8p5r0F+px5jR7ZYCXu92BNBl6w0334HBey6vfPlYM=,tag:5dDGal1QvODHcKGtUrveMA==,type:str]
kind: Secret
metadata:
    name: truenas-api-credentials
    namespace: truenas-csi
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbTV3cmxrVE1xbjVJcWE5
            SXpnREhObDlsL3ZqVmVZdklUbkZsTDlaYkdRCjEyVkRCamJseHhKYmJmV0s4TVpX
            NEtnZlBMcnlXQSswYllnUHdHb2c4ZFkKLS0tIGRuMWxjSHBjaFczd1I2UHFhaysz
            YkJXMTZrVHllQW5zWnJ3ZlhmQlpVb2MKWZuASXletqjw39L4Y2C9xzSSzCJWX5Qz
            JMABIGxKGl1Y87/ccSXe9IzdJDGmJ45U66mNdfWZYP18PaNnxN1WKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tuevyl5qpv4cl38effc5vandvgqtrsa6pn3fwsz4m34lyaksfvkqdfwnxf
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-03T14:34:49Z"
    mac: ENC[AES256_GCM,data:tmZnwrTGaSPPDYspaFq7dfBfUJUutAH5naI+H0X/i1NX8+QRAGL3wR/S1WF127oZmrncXBoj5yGG8OYgxMNE4ALMnUgZOn+u2WzxOTalep4In3p1nbvZ8WqBUFrSEdPkgKrr17A4Xi7SiIutSyiTfDsVlAKRBy6WX7wiXQ3/9XE=,iv:4zptlhX41oEItQzp6ZEPQIKqvsmuJ5AFfMezqDEi6W4=,tag:kYjCuqkcEswCl4lTegWCOA==,type:str]
    version: 3.13.3
