apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: truenas-csi-node
  namespace: truenas-csi
spec:
  template:
    spec:
      containers:
        - name: csi-node
          volumeMounts:
            - name: iscsi-dir
              mountPath: /etc/iscsi
              $patch: delete
      volumes:
        - name: iscsi-dir
          $patch: delete
